### ISSUE TITLE
Add ability to parse a different tag name than 'Trans'

### ISSUE THREAD

**Issue by CynthiaXJia** [gilbsgilbs/babel-plugin-i18next-extract#44] opened 2019-08-16 16:33 UTC
I've written a custom Trans component, MyTrans, and in the code it is used exactly like Trans would be (ie `<MyTrans i18nKey="myKey"> Some stuff to translate </MyTrans>`). Is there an option similar to the 'i18nInstanceNames' where we can specify a name for Trans extraction / would it be possible to add?

**Comment by gilbsgilbs** [comment] 2019-08-16 17:06
Hey! This is a duplicate of #33. I'm afraid it is not possible at the moment.

**Closed by gilbsgilbs** 2019-08-16 17:06 UTC
