### ISSUE TITLE
Enable/Disable sort for keys

### ISSUE THREAD

**Issue by fnavarrodev** [gilbsgilbs/babel-plugin-i18next-extract#161] opened 2020-06-04 05:58 UTC
It would be great to be able to configure the plugin so you could enable/disable sorting of keys. Our tool for translating uses alphabetical(not case sensitive) order and every time we use the tool we get a different order than the one from extracting. Maybe json-stable-stringify has an option to order not case-sensitive like a SORT from SQL does?

**Comment by gilbsgilbs** [comment] 2020-09-30 20:25
Hi! Thanks for raising an issue and sorry for the delay. Closing as a duplicate of #59. Feel free to re-open if you think I'm wrong.

**Closed by gilbsgilbs** 2020-09-30 20:25 UTC
